name = "EVB 6 OPTI"
author = "Al Baida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "745998e7f9e450f32bfbb81c7662d4206e7d6c9e6a9ec3acafc7cc86a67af7f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
